openline-ai/openline-contacts

- components/GridComponent.tsx
- pages/contact/[id].tsx
- pages/contactGroup/[id].tsx
- Delete contact
- Delete group
> Delete contact and contact group

- .gitignore
- README.md
- deployment/debug-install.sh
- deployment/full-install.sh
- deployment/prerequisites-install.sh
- config for running contacts apps in debug
- config for running contacts apps full in k8s
> Minikube installer rework

- contacts-gui/components/SearchComponent.tsx
- contacts-gui/pages/contact/[id].tsx
- contacts-gui/pages/contact/contactCompanyPositionTemplate.tsx
- New search component ( dropdown style + overlay panel with search and select item )
- Owner field in customer
> Contact owner

- contacts-gui/components/GridComponent.tsx
- contacts-gui/pages/contact/index.tsx
- contacts-gui/pages/contactGroup/index.tsx
- Rework sorting component to support multiple fields
- Add sorting to contacts grid
> Contacts grid sorting

- components/contact/contactCompanyPositionTemplate.tsx
- components/contact/contactDetailsSection.tsx
- components/contact/contactEmailTemplate.tsx
- components/contact/contactExtensionSection.tsx
- components/contact/contactPhoneNumberTemplate.tsx
- components/generic/GridComponent.tsx
- components/generic/SearchComponent.tsx
- components/generic/SearchOrAddComponent.tsx
- layout/layout.tsx
- models/contactGroup.ts
- package.json
- pages/_app.tsx
- pages/contact/[id].tsx
- pages/contact/index.tsx
- pages/contactGroup/[id].tsx
- pages/contactGroup/index.tsx
- services/contactGroupService.ts
- services/contactService.ts
- yarn.lock
- contact type readonly after creation
- notifications on actions and errors
- move contact group queries to service class
> Improvements

- deployment/infra/k8s/contacts-gui-deployment.yaml
> update image url

- packages/apps/contacts/package.json
- packages/apps/contacts/yarn.lock
> Upgrade webchat

- packages/apps/contacts/components/atoms/button/Button.tsx
- packages/apps/contacts/components/atoms/icon-button/IconButton.tsx
- packages/apps/contacts/components/atoms/icon-button/icon-button.module.scss
- packages/apps/contacts/components/contact/contactChannels.tsx
- packages/apps/contacts/components/contact/contactDetailsSection.tsx
- packages/apps/contacts/components/contact/details-page-layout/DetailsPageLayout.tsx
- packages/apps/contacts/components/contact/details-page-layout/ProfileLayout.tsx
- packages/apps/contacts/components/contact/details-page-layout/details-page-layout.module.scss
- packages/apps/contacts/components/contact/details-page-layout/utils.ts
- packages/apps/contacts/pages/contact/[id].tsx
> (fix) #189 Fixed add / edit contact details bug

- packages/apps/contacts/components/contact/contactDetailsSection.tsx
- packages/apps/contacts/components/contact/details-page-layout/DetailsPageLayout.tsx
- packages/apps/contacts/components/contact/details-page-layout/ProfileLayout.tsx
- packages/apps/contacts/components/contact/details-page-layout/details-page-layout.module.scss
- packages/apps/contacts/styles/theme-override.css
User update action created duplicates user this mr fixes that and edit form behaviour (form is fed with existing data  in edit mode)
> (fix) #191 Fixed user duplication on user update issue

- packages/apps/contacts/pages/settings/index.tsx
> (fix) Fix for demo

- packages/apps/contacts/components/atoms/button/Button.tsx
- packages/apps/contacts/components/atoms/button/button.module.scss
- packages/apps/contacts/models/settings.ts
- packages/apps/contacts/pages/settings/index.tsx
- packages/apps/contacts/services/settingsService.ts
#201 Add ability to revoke access
> (feat) #200 Add smartsheet configuration

- packages/apps/contacts/components/organisms/side-panel/side-panel.module.scss
- packages/apps/contacts/pages/_app.tsx
- packages/apps/contacts/pages/settings/index.tsx
> Add margin to settings and add title to app

- packages/apps/contacts/components/contact/details-page-layout/ProfileLayout.tsx
- packages/apps/contacts/components/molecules/conversation-timeline-item/ConversationTimelineItem.tsx
- packages/apps/contacts/components/organization/EditOrganization.tsx
- [ x] Bugfix (non-breaking change which fixes an issue)
> #231 Feed user loading fix

- packages/apps/contacts/components/atoms/cardHeading/CardHeading.tsx
- packages/apps/contacts/components/contact/ContactList.tsx
- packages/apps/contacts/components/contact/note/contactNoteModalTemplate.tsx
- packages/apps/contacts/components/generic/GridComponent.tsx
- packages/apps/contacts/model/enum-contactTitle.ts
- packages/apps/contacts/styles/globals.css
#175: Typo in Gui 
#242: Remove title from grid view on contact list 
#208: Industry text change #208 
#209: Table pagination state should be remembered when user navigates… 
#235: Fixed ghost table row after removing contact personal data
> fix: Fixes for contacts app related bugs

- packages/apps/contacts/components/organization/ConversationHistory.tsx
[x] Bugfix (non-breaking change which fixes an issue)
> fix: #253 Clear organisation timeline from duplicated events

- packages/apps/contacts/components/molecules/conversation-timeline-item/ConversationTimelineItem.tsx
[x] Bugfix (non-breaking change which fixes an issue)
> fix: #251 Removed phantom communications from timeline

- packages/apps/contacts/components/contact/details-page-layout/DetailsPageLayout.tsx
- packages/apps/contacts/components/contact/details-page-layout/ProfileLayout.tsx
- packages/apps/contacts/components/contact/details-page-layout/details-page-layout.module.scss
- packages/apps/contacts/components/molecules/note-timeline-item/NoteTimelineItem.tsx
- packages/apps/contacts/models/contact.ts
- packages/apps/contacts/services/contactService.ts
- packages/apps/contacts/services/organizationService.ts
> feat: #173: Display contact source on contact source panel

- packages/apps/contacts/components/organization/ConversationHistory.tsx
> fix: #289 Organisation fix

- packages/apps/contacts/components/organization/ConversationHistory.tsx
> fix: #289 Organisation fix (#296)

- packages/apps/contacts/models/organization.ts
- packages/apps/contacts/pages/organization/[id].tsx
- packages/apps/contacts/services/organizationService.ts
- [ x] New feature (non-breaking change which adds functionality)
> feat: #291 Use new Api version to fetch contacts for an organisation

- packages/apps/contacts/components/molecules/conversation-timeline-item/ConversationTimelineItem.tsx
- packages/apps/contacts/components/molecules/note-timeline-item/note.module.scss
- packages/apps/contacts/services/organizationService.ts
#324 [Removed underline text decoration](https://github.com/openline-ai/openline-contacts/commit/52e51490154b25173d2d4e7cfcc71b5f31488536)
#327 [Fixed update organization bug](https://github.com/openline-ai/openline-contacts/commit/f397aaf87c74f30e77ead9c66c138296ca330a24)
#326 [Sort emails in reverse chronological order](https://github.com/openline-ai/openline-contacts/commit/9d5af061c562c2edaa8729fa6ce67d1733b47c70)
> Fix: #327 #326  #324 Batch fix
